# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OVVVMGu68TWg-FD7C-tUJB09iA9hkosJ
"""

from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten, Dropout
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# 1) Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

import os
src_path = "/content/drive/MyDrive/Palmistry"

# Kiểm tra thư mục
print("Classes:", os.listdir(src_path))

# 2) Import + tạo generator với resize 60x60 và tách validation 20%
from tensorflow.keras.preprocessing.image import ImageDataGenerator

datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.5,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'
)

train_generator = datagen.flow_from_directory(
    src_path,
    target_size=(60, 60),
    batch_size=32,
    class_mode='categorical',
    subset='training',   # train subset
    shuffle=True
)

val_generator = datagen.flow_from_directory(
    src_path,
    target_size=(60, 60),
    batch_size=32,
    class_mode='categorical',
    subset='validation',  # validation subset
    shuffle=False
)

# 3) Build CNN model
from tensorflow.keras import layers, models

num_classes = train_generator.num_classes

model = models.Sequential([
    layers.Input(shape=(60, 60, 3)),
    layers.Conv2D(32, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(num_classes, activation='softmax')
])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

# 4) Train model
history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=200
)
model.save('final_model.h5')

from google.colab import files
import cv2
import numpy as np
import matplotlib.pyplot as plt

# Upload ảnh
uploaded = files.upload()
img_path = list(uploaded.keys())[0]

# Đọc + resize về 60x60
img = cv2.imread(img_path)
img_resized = cv2.resize(img, (60, 60))
img_array = img_resized / 255.0
img_array = np.expand_dims(img_array, axis=0)

# Dự đoán
pred = model.predict(img_array)
class_index = np.argmax(pred)
confidence = np.max(pred)

labels = list(train_generator.class_indices.keys())
print("Dự đoán:", labels[class_index], "- Độ tin cậy:", confidence)

# Hiển thị ảnh
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title(f"Dự đoán: {labels[class_index]} ({confidence:.2f})")
plt.axis("off")
plt.show()

import gradio as gr
import numpy as np
from PIL import Image
from tensorflow.keras.models import load_model

# Load model CNN nhận diện chỉ tay
model_path = 'final_model.h5'  # đổi theo đường dẫn model của bạn
model = load_model(model_path)

# Nhãn các loại chỉ tay (thứ tự phải trùng với model training)
palm_labels = [
    "Chỉ tay chữ M",
    "Chỉ tay chữ nhất",
    "Chỉ tay đuôi cá",
    "Chỉ tay mắt phượng",
    "Chỉ tay thỏi vàng"
]

# Thông tin chi tiết về từng loại chỉ tay
palmistry_info = {
    "Chỉ tay chữ M": "Người có đường chỉ tay chữ M thường được cho là có tài năng đặc biệt, thông minh, và may mắn. Họ có khả năng lãnh đạo, trực giác tốt và thường đạt được thành công lớn trong sự nghiệp và cuộc sống.",
    "Chỉ tay chữ nhất": "Người có đường chỉ tay chữ Nhất thường có tính cách mạnh mẽ và quyết đoán. Họ có khả năng tập trung cao độ và thường đạt được thành công trong những lĩnh vực đòi hỏi sự kiên trì và quyết tâm. Tuy nhiên, họ cũng có thể gặp khó khăn trong việc cân bằng giữa lý trí và cảm xúc.",
    "Chỉ tay đuôi cá": "Người có đường chỉ tay đuôi cá thường được coi là có may mắn đặc biệt và thường gặp được nhiều cơ hội tốt trong cuộc sống. Họ có khả năng vượt qua khó khăn và đạt được thành công lớn.",
    "Chỉ tay mắt phượng": "Người có đường chỉ tay mắt phượng thường có trực giác tốt, trí tuệ cao và khả năng nhìn xa trông rộng. Họ thường được quý nhân phù trợ và có nhiều cơ hội thành công trong cuộc sống.",
    "Chỉ tay thỏi vàng": "Người có đường chỉ tay thỏi vàng thường được cho là có tài lộc, thịnh vượng và thành công trong sự nghiệp. Họ có khả năng quản lý tài chính tốt và thường gặp may mắn trong kinh doanh.",
}

# Hàm dự đoán
def predict_palm(img):
    img_resized = img.convert("RGB").resize((60,60))  # Resize về 60x60 (theo model bạn train)
    x = np.array(img_resized)/255.0
    x = np.expand_dims(x, axis=0)
    preds = model.predict(x)
    class_idx = np.argmax(preds)
    confidence = preds[0][class_idx]

    palm_type = palm_labels[class_idx]
    description = palmistry_info.get(palm_type, "Chưa có thông tin.")
    return img_resized, palm_type, round(confidence*100, 2), description

# Hàm reset
def reset_image():
    return None, None, "", "", ""

# CSS giao diện huyền bí
css_style = """
body {
    background: radial-gradient(circle at top, #1c0033, #0a0014);
    font-family: 'Poppins', sans-serif;
    color: #f3e5f5;
}
h1 {
    color: #ffffff;  /* trắng sáng thay vì tím nhạt */
    text-shadow: 0px 0px 20px #e1bee7, 0px 0px 40px #ba68c8;
    font-family: 'Orbitron', sans-serif;
    font-size: 42px;
    font-weight: bold;
    letter-spacing: 2px;
}
#predict-btn {
    background: linear-gradient(45deg, #6a1b9a, #311b92);
    color: #fff;
    font-weight: bold;
    font-size: 18px;
    border-radius: 25px;
    box-shadow: 0px 0px 10px #7e57c2;
}
#reset-btn {
    background: linear-gradient(45deg, #004d40, #1a237e);
    color: #fff;
    font-weight: bold;
    font-size: 18px;
    border-radius: 25px;
    box-shadow: 0px 0px 10px #26a69a;
}
.gr-button {padding: 12px 25px;}
.gr-box {
    border: 2px solid #7e57c2;
    border-radius: 20px;
    padding: 15px;
    background-color: rgba(20, 0, 40, 0.85);
    color: #e1bee7;
}
"""

# Giao diện Gradio
with gr.Blocks(css=css_style) as demo:
    gr.Markdown("<h1 style='text-align:center;'>🔮 Ứng dụng bói chỉ tay online ✋</h1>")

    with gr.Row():
        with gr.Column():
            img_input = gr.Image(type="pil", label="✨ Chọn ảnh hoặc kéo thả ảnh chỉ tay ✨")
            btn_predict = gr.Button("🔮 Nhận diện ✋", elem_id="predict-btn")
            btn_reset = gr.Button("🔄 Chọn ảnh khác", elem_id="reset-btn")
        with gr.Column():
            label_output = gr.Textbox(label="🔮 Loại chỉ tay dự đoán", interactive=False)
            confidence_output = gr.Textbox(label="📊 Độ chính xác (%)", interactive=False)
            description_output = gr.Textbox(label="📖 Miêu tả chi tiết", interactive=False, lines=6)

    # Nút dự đoán
    btn_predict.click(
        predict_palm,
        inputs=img_input,
        outputs=[img_resized_output, label_output, confidence_output, description_output]
    )

    # Nút reset
    btn_reset.click(
        reset_image,
        inputs=None,
        outputs=[img_input, img_resized_output, label_output, confidence_output, description_output]
    )

# Chạy app
demo.launch(share=True)